const SUPABASE_URL = "https://bjmjqvlinklexwfudrfv.supabase.co";
const SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbWpxdmxpbmtsZXh3ZnVkcmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyMTUxNTUsImV4cCI6MjA5Mjc5MTE1NX0.ss84j3h9QtrSgGu3oSIvPHtnmshjo59E9wTxmmPFtSo";
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON);
